test: usage test improvements

diff --git a/.github/workflows/integration-platform.yaml b/.github/workflows/integration-platform.yaml
--- a/.github/workflows/integration-platform.yaml
+++ b/.github/workflows/integration-platform.yaml
@@ -99,16 +99,16 @@ jobs:
         print(f"Installed neuracore version: {neuracore.__version__}")
         EOF
 
-    - name: Run Consume Stream Integration Test
-      env:
-        NEURACORE_API_URL: ${{ matrix.environment == 'staging' && 'https://staging.api.neuracore.com/api' || 'https://api.neuracore.com/api' }}
-        NEURACORE_API_KEY: ${{ matrix.environment == 'staging' && secrets.STAGING_SERVICE_API_KEY || secrets.PROD_SERVICE_API_KEY }}
-        NEURACORE_ORG_ID: ${{ matrix.environment == 'staging' && vars.STAGING_SERVICE_ORG_ID || vars.PROD_SERVICE_ORG_ID }}
-      continue-on-error: true
-      run: |
-        if ! pytest -o log_cli=true --log-cli-level=INFO tests/integration/platform/test_consume_stream.py; then
-          echo "::warning::test_consume_stream.py failed, but this is non-blocking."
-        fi
+    # - name: Run Consume Stream Integration Test
+    #   env:
+    #     NEURACORE_API_URL: ${{ matrix.environment == 'staging' && 'https://staging.api.neuracore.com/api' || 'https://api.neuracore.com/api' }}
+    #     NEURACORE_API_KEY: ${{ matrix.environment == 'staging' && secrets.STAGING_SERVICE_API_KEY || secrets.PROD_SERVICE_API_KEY }}
+    #     NEURACORE_ORG_ID: ${{ matrix.environment == 'staging' && vars.STAGING_SERVICE_ORG_ID || vars.PROD_SERVICE_ORG_ID }}
+    #   continue-on-error: true
+    #   run: |
+    #     if ! pytest -o log_cli=true --log-cli-level=INFO tests/integration/platform/test_consume_stream.py; then
+    #       echo "::warning::test_consume_stream.py failed, but this is non-blocking."
+    #     fi
 
     - name: Run Data Daemon Integration Tests
       env:
